### PR TITLE
#160577629-User like or dislike  a comment

### PR DESCRIPTION
**Pull request by YAHYA-H**
## What does this PR do
Allows users to like or dislike a comment(s)

## Description of a task to be completed.
Users should be able to like a specific comment or dislike 
but not all both of it in one comment

| Endpoint        | Functionality        
| ------------- |-------------| 
| PUT api/articles/slug/comments/pk/like| Like or unlike liked  comment |
| PUT api/articles/slug/comments/pk/dislike| Dislike or unlike disliked comment |

Screenshot
image
image

## Relevant Pivotal Tracker Stories
[#160577629](https://www.pivotaltracker.com/story/show/160577629)

### CODE REVIEW

**Comment by gitaumoses4** [comment]
Have you rebased onto develop?

**Comment by YAHYA-H** [comment]
> Have you rebased onto develop?
yeah, i branched off from develop and then rebased from my comment feature @gitaumoses4

**Comment by esirK** [comment]
> > Have you rebased onto develop?
> > yeah, i branched off from develop and then rebased from my comment feature @gitaumoses4

All this commits unrelated to your task should then not be appearing.

**Comment by YAHYA-H** [comment]
> > > Have you rebased onto develop?
> > > yeah, i branched off from develop and then rebased from my comment feature @gitaumoses4
> 
> All this commits unrelated to your task should then not be appearing.

@esirK  i rebased from comment feature, how do I remove all unrelated commits? because i need the comment feature inorder to like and dislike a comment

**Comment by mutaimwiti** [comment]
@YAHYA-H Please consider renaming this branch to `ft-comment-like-dislike-160577629` to conform to our Git naming convections.

**Pull request closed without merging**
