### PR TITLE
#160577617 enable users to favorite articles

### PR DESCRIPTION
**Pull request by C3real-kill3r**
## What does this PR do?
It allows an authorized user to either favorite or unfavourite an article.

## What is its significance?
Articles that tickle a users fancy are worth favoriting and those deemed distasteful are worth unfavoriting.

## How to manually test it?
To update dependencies
* pip install -r requirements.txt
 
Run server

* python manage.py runserver
* Navigate to the endpoint below through Postman

| Endpoint        | Functionality        
| ------------- |-------------| 
| POST api/articles/<slug>/favourite| Adds to favorites the articles whose slug has been specified on the url |
| DELETE api/articles/<slug>/favourite| Removes from favorites the articles whose slug has been specified on the url |

* on successful favorite;
screen shot 2018-10-08 at 15 20 51

* On successful unfavourite;
screen shot 2018-10-08 at 15 21 13

## What are the relevant PT?
[160577617](https://www.pivotaltracker.com/story/show/160577617)

### CODE REVIEW

**Comment by gitaumoses4** [comment]
Good work on the task. 👍 
Great improvement on the coverage. Looks good.

**Comment by gitaumoses4** [comment]
@C3real-kill3r Do you have an endpoint for listing all the favourited articles for the logged in user?

**Comment by esirK** [comment]
Looks good. Fix the conflicts.

**Comment by C3real-kill3r** [comment]
> Looks good. Fix the conflicts.

Done

**Pull request merged**
