### PR TITLE
#160577602 configure posgresql db 

### PR DESCRIPTION
**Pull request by C3real-kill3r**
## What does this PR do?
* It adds psycopg2 to the requirements.txt file

## What are the relevant PT stories?
[160577602](https://www.pivotaltracker.com/story/show/160577602)

### CODE REVIEW

**Comment by mutaimwiti** [comment]
I really need this in order to test PR deployments. I'm blocked because I need to use Postgres on Heroku.

**Comment by esirK** [comment]
We already have this changes on develop.

**Review by mutaimwiti — APPROVED** [review]
I think this is very straightforward. It fixes the DB issue I have with deployments.

**Comment by esirK** [comment]
@mutaimwiti  sure. What I mean is we don't need all these changes again. We only need the `requirements.txt` file changes

**Comment by C3real-kill3r** [comment]
Closing. I will open another one shortly.

**Pull request closed without merging**
